const $=id=>document.getElementById(id); let mode='text';
const LABELS={ADMISSION_DISCHARGE:'Admission / Discharge',RADIOLOGY_REPORT:'Radiology Report',PATHOLOGY_REPORT:'Pathology Report',LABORATORY_REPORT:'Laboratory Report',EMERGENCY_REPORT:'Emergency Report',ADMISSION_NOTE:'Admission Note',DISCHARGE_SUMMARY:'Discharge Summary',PUBLIC_HEALTH_DOCUMENT:'Public Health Document',X_RAY:'X-ray',NUCLEAR_MEDICINE:'Nuclear Medicine',ENGLISH:'English',ARABIC:'Arabic',MIXED:'Mixed Arabic / English',WITH_CONTRAST:'With contrast',WITHOUT_CONTRAST:'Without contrast',PRE_AND_POST_CONTRAST:'Pre/Post Contrast'};
function label(v){const s=String(v||'UNKNOWN');return LABELS[s]||s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function uncertain(p){return p.document_type==='UNKNOWN'||['LOW','UNKNOWN'].includes(p.confidence_band)}
function setMode(next){mode=next;$('textTab').classList.toggle('active',next==='text');$('fileTab').classList.toggle('active',next==='file');$('textMode').style.display=next==='text'?'block':'none';$('fileMode').classList.toggle('active',next==='file');$('status').textContent=''}
function renderList(target,items,render,empty){target.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='empty';e.textContent=empty;target.append(e);return}items.forEach(x=>target.append(render(x)))}
function renderRows(target,rows){target.replaceChildren();rows.filter(([,value])=>value!==null&&value!==undefined&&value!==''&&(!(Array.isArray(value))||value.length)).forEach(([key,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=Array.isArray(value)?value.map(label).join(' · '):value;row.append(dt,dd);target.append(row)})}
function recognitionReasons(evidence){const seen=new Set(),reasons=[];for(const item of evidence||[]){let reason;switch(item.category){case 'context':reason='Radiology report context identified';break;case 'modality':reason=`${label(item.signal)} imaging modality identified`;break;case 'technique':reason='Imaging technique identified';break;case 'acquisition':reason='Image acquisition context identified';break;case 'anatomy':reason='Anatomical study region identified';break;case 'contrast':reason='Contrast context identified';break;case 'section':reason=`${label(item.signal)} section identified`;break;case 'professional_role':reason='Radiology professional attribution identified';break;case 'clinical_purpose':reason='Clinical purpose context identified';break;default:continue}if(!seen.has(reason)){seen.add(reason);reasons.push(reason)}}return reasons}
function renderSemanticContext(clinical){const radiology=clinical.domain_extension||null;if(!radiology){$('semanticCard').hidden=true;return}const modality=radiology.modality||clinical.modality,typed=modality==='ULTRASOUND'&&radiology.modality_context?.doppler_present?'Ultrasound':label(modality);const rows=[['Study / Examination',radiology.examination],['Modality',typed],['Study Context',radiology.modality_context?.doppler_present?'Doppler / Vascular Ultrasound':null],['Primary Study Anatomy',radiology.authoritative_anatomy],['Body Region',(radiology.body_regions||[]).length?(radiology.body_regions||[]):radiology.body_region&&label(radiology.body_region)],['Contrast',radiology.contrast&&label(radiology.contrast)],['Clinical Purpose',clinical.clinical_purpose],['Technique / Acquisition',radiology.techniques||[]],['Report Context',radiology.finding_bearing?'Findings narrative identified':null]];renderRows($('semanticList'),rows);const specific=radiology.modality_context||null;let title='',specificRows=[];if(specific){if('sequence_families'in specific){title='MRI Context';specificRows=[['Sequence Families',specific.sequence_families||[]],['Multiplanar Acquisition',specific.multiplanar_acquisition_present?'Yes':null]]}else if('angiographic_context'in specific){title='CT Context';specificRows=[['Angiographic Context',specific.angiographic_context?'Yes':null],['Multiplanar Reconstruction',specific.multiplanar_reconstruction_present?'Yes':null]]}else if('views'in specific){title='X-ray Context';const count=specific.view_count?`${specific.view_count}${specific.view_count_qualifier==='OR_MORE'?' or more':''}`:null;specificRows=[['Named Views',specific.views||[]],['View Count',count]]}else if('doppler_present'in specific){title='Ultrasound Context';specificRows=[['Doppler',specific.doppler_present?'Yes':null],['Imaging Modes',specific.imaging_modes||[]]]}}renderRows($('modalityContextList'),specificRows);$('modalityContextTitle').textContent=title;$('modalityContext').hidden=!specificRows.some(([,value])=>value!==null&&value!==undefined&&value!==''&&(!Array.isArray(value)||value.length));$('semanticNote').hidden=!radiology.finding_bearing;$('semanticCard').hidden=!rows.some(([,value])=>value!==null&&value!==undefined&&value!==''&&(!Array.isArray(value)||value.length))}
function render(p){
 const low=uncertain(p),ctx=p.document_context||{},identity=ctx.identity||{},clinical=ctx.clinical_context||{},route=p.routing||{};
 $('domainValue').textContent=low?'Document context requires review':label(p.domain);
 $('documentSummary').textContent=low?'Healthcare domain and document type are not determined':[label(p.document_type),clinical.examination].filter(Boolean).join(' · ');
 $('languageValue').textContent=p.language==='UNKNOWN'?'Language not identified':label(p.language);
 $('confidenceBand').textContent=`${label(p.confidence_band)} recognition confidence`;
 $('confidenceNote').textContent=low?'MedNexus could not identify the document reliably.':'Strong evidence supports this document context.';
 $('recognitionSummary').classList.toggle('low',low);
 const rows=[['Healthcare Domain',low?'Not determined':label(identity.healthcare_domain||p.domain)],['Document Type',low?'Not determined':label(identity.document_type||p.document_type)],['Subtype / Modality',p.document_subtype!=='UNKNOWN'&&label(p.document_subtype)],['Primary Language',label(p.language)],['Recognition Confidence',label(p.confidence_band)]].filter(([,v])=>v&&v!=='Unknown');
 $('overviewList').replaceChildren();rows.forEach(([k,v])=>{const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;d.append(dt,dd);$('overviewList').append(d)});
 renderSemanticContext(clinical);
 renderList($('sectionList'),ctx.structure||[],s=>{const d=document.createElement('div');d.className='structure-item';d.textContent=s.semantic_role;return d},'No structural sections detected.');
 const reasons=(p.recognition_explanations||[]).length?p.recognition_explanations.map(x=>x.message):recognitionReasons(p.evidence);renderList($('recognitionReasons'),reasons,x=>{const d=document.createElement('div'),i=document.createElement('i'),s=document.createElement('span');d.className='simple-item';i.textContent='✓';s.textContent=x;d.append(i,s);return d},'No additional recognition evidence available.');
 $('journeyTitle').textContent=route.manual_review_required?'Manual review recommended.':'Document context established.';$('routeNote').textContent=route.manual_review_required?'MedNexus found some context, but not enough evidence to classify it reliably.':'Continue with this same document and context—no second upload required.';$('continueBtn').hidden=!!route.manual_review_required;$('continueBtn').onclick=()=>{if(p.journey?.continue_to_protect)location.href=p.journey.continue_to_protect};
 const sections=p.sections||[],evidence=p.evidence||[];$('machineDetails').textContent=JSON.stringify({domain:p.domain,document_type:p.document_type,document_subtype:p.document_subtype,language:p.language,confidence:p.confidence,confidence_band:p.confidence_band,journey_id:p.journey?.journey_id,clinical_context:clinical},null,2);
 renderList($('technicalSections'),sections,s=>{const d=document.createElement('div');d.className='technical-row';d.textContent=`${s.canonical_name} · “${s.original_heading}” · ${s.start}–${s.end}`;return d},'No section offsets.');
 renderList($('technicalEvidence'),evidence,e=>{const d=document.createElement('div');d.className='technical-row';const b=document.createElement('b'),s=document.createElement('span');b.textContent=`${e.category} · weight ${e.weight}${e.concept_id?` · ${e.concept_id}`:''}`;s.textContent=`${e.signal}${e.reference?` · matched “${e.reference}”`:''}${e.reference_systems?.length?` · ${e.reference_systems.join(', ')}`:''}`;d.append(b,s);return d},'No knowledge evidence.');
 $('technicalRouting').textContent=JSON.stringify(route,null,2);document.querySelector('.technical-details').removeAttribute('open');const warnings=p.warnings||[];$('warnings').classList.toggle('show',warnings.length>0);$('warnings').textContent=warnings.length?`Warnings: ${warnings.join(' · ')}`:'';$('results').classList.add('show');$('results').scrollIntoView({behavior:'smooth'});
}
async function analyze(){try{$('analyzeBtn').disabled=true;$('status').textContent='Establishing document context…';let r;if(mode==='text'){const text=$('textInput').value.trim();if(!text)throw Error('Paste medical document text before analysis.');r=await fetch('/api/v1/understanding/analyze-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})})}else{const f=$('fileInput').files[0];if(!f)throw Error('Choose a supported document before analysis.');const fd=new FormData();fd.append('file',f);r=await fetch('/api/v1/understanding/analyze-file',{method:'POST',body:fd})}const p=await r.json();if(!r.ok)throw Error(p.detail||'MedNexus could not understand this document.');render(p);$('status').textContent=''}catch(e){$('status').textContent=e.message||'MedNexus could not understand this document.'}finally{$('analyzeBtn').disabled=false}}
$('textTab').onclick=()=>setMode('text');$('fileTab').onclick=()=>setMode('file');$('fileInput').onchange=()=>{$('fileName').textContent=$('fileInput').files[0]?.name||'No file selected'};$('analyzeBtn').onclick=analyze;$('anotherBtn').onclick=()=>{$('results').classList.remove('show');$('workspace').scrollIntoView({behavior:'smooth'})};
