const $=id=>document.getElementById(id); let mode='text';
const LABELS={ADMISSION_DISCHARGE:'Admission / Discharge',RADIOLOGY_REPORT:'Radiology Report',PATHOLOGY_REPORT:'Pathology Report',LABORATORY_REPORT:'Laboratory Report',EMERGENCY_REPORT:'Emergency Report',ADMISSION_NOTE:'Admission Note',DISCHARGE_SUMMARY:'Discharge Summary',PUBLIC_HEALTH_DOCUMENT:'Public Health Document',X_RAY:'X-ray',NUCLEAR_MEDICINE:'Nuclear Medicine',ENGLISH:'English',ARABIC:'Arabic',MIXED:'Mixed Arabic / English',WITH_CONTRAST:'With contrast',WITHOUT_CONTRAST:'Without contrast'};
function label(v){const s=String(v||'UNKNOWN');return LABELS[s]||s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function uncertain(p){return p.document_type==='UNKNOWN'||['LOW','UNKNOWN'].includes(p.confidence_band)}
function setMode(next){mode=next;$('textTab').classList.toggle('active',next==='text');$('fileTab').classList.toggle('active',next==='file');$('textMode').style.display=next==='text'?'block':'none';$('fileMode').classList.toggle('active',next==='file');$('status').textContent=''}
function renderList(target,items,render,empty){target.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='empty';e.textContent=empty;target.append(e);return}items.forEach(x=>target.append(render(x)))}
function render(p){
 const low=uncertain(p),ctx=p.document_context||{},identity=ctx.identity||{},clinical=ctx.clinical_context||{},route=p.routing||{};
 $('domainValue').textContent=low?'Document context requires review':label(p.domain);
 $('documentSummary').textContent=low?'Healthcare domain and document type are not determined':[label(p.document_type),clinical.examination].filter(Boolean).join(' · ');
 $('languageValue').textContent=p.language==='UNKNOWN'?'Language not identified':label(p.language);
 $('confidenceBand').textContent=`${label(p.confidence_band)} recognition confidence`;
 $('confidenceNote').textContent=low?'MedNexus could not identify the document reliably.':'Strong evidence supports this document context.';
 $('recognitionSummary').classList.toggle('low',low);
 const rows=[['Healthcare Domain',low?'Not determined':label(identity.healthcare_domain||p.domain)],['Document Type',low?'Not determined':label(identity.document_type||p.document_type)],['Examination',clinical.examination],['Modality',clinical.modality],['Contrast',clinical.contrast&&label(clinical.contrast)],['Body Region',clinical.body_region&&label(clinical.body_region)],['Primary Language',label(p.language)],['Recognition Confidence',label(p.confidence_band)]].filter(([,v])=>v&&v!=='Unknown');
 $('overviewList').replaceChildren();rows.forEach(([k,v])=>{const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;d.append(dt,dd);$('overviewList').append(d)});
 renderList($('sectionList'),ctx.structure||[],s=>{const d=document.createElement('div');d.className='structure-item';d.textContent=s.semantic_role;return d},'No structural sections detected.');
 const items=[clinical.examination,clinical.modality&&`${label(clinical.modality)} imaging`,clinical.contrast&&label(clinical.contrast),clinical.body_region&&`${label(clinical.body_region)} region`].filter(Boolean);
 renderList($('clinicalContextList'),[...new Set(items)],x=>{const s=document.createElement('span');s.textContent=x;return s},'No additional domain-specific clinical context identified.');
 $('journeyTitle').textContent=route.manual_review_required?'Manual review recommended.':'Document context established.';$('routeNote').textContent=route.manual_review_required?'MedNexus found some context, but not enough evidence to classify it reliably.':'Continue with this same document and context—no second upload required.';$('continueBtn').hidden=!!route.manual_review_required;$('continueBtn').onclick=()=>{if(p.journey?.continue_to_protect)location.href=p.journey.continue_to_protect};
 const sections=p.sections||[],evidence=p.evidence||[];$('machineDetails').textContent=JSON.stringify({domain:p.domain,document_type:p.document_type,document_subtype:p.document_subtype,language:p.language,confidence:p.confidence,confidence_band:p.confidence_band,journey_id:p.journey?.journey_id,clinical_context:clinical},null,2);
 renderList($('technicalSections'),sections,s=>{const d=document.createElement('div');d.className='technical-row';d.textContent=`${s.canonical_name} · “${s.original_heading}” · ${s.start}–${s.end}`;return d},'No section offsets.');
 renderList($('technicalEvidence'),evidence,e=>{const d=document.createElement('div');d.className='technical-row';const b=document.createElement('b'),s=document.createElement('span');b.textContent=`${e.category} · weight ${e.weight}${e.concept_id?` · ${e.concept_id}`:''}`;s.textContent=`${e.signal}${e.reference?` · matched “${e.reference}”`:''}${e.reference_systems?.length?` · ${e.reference_systems.join(', ')}`:''}`;d.append(b,s);return d},'No knowledge evidence.');
 $('technicalRouting').textContent=JSON.stringify(route,null,2);document.querySelector('.technical-details').removeAttribute('open');const warnings=p.warnings||[];$('warnings').classList.toggle('show',warnings.length>0);$('warnings').textContent=warnings.length?`Warnings: ${warnings.join(' · ')}`:'';$('results').classList.add('show');$('results').scrollIntoView({behavior:'smooth'});
}
async function analyze(){try{$('analyzeBtn').disabled=true;$('status').textContent='Establishing document context…';let r;if(mode==='text'){const text=$('textInput').value.trim();if(!text)throw Error('Paste medical document text before analysis.');r=await fetch('/api/v1/understanding/analyze-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})})}else{const f=$('fileInput').files[0];if(!f)throw Error('Choose a supported document before analysis.');const fd=new FormData();fd.append('file',f);r=await fetch('/api/v1/understanding/analyze-file',{method:'POST',body:fd})}const p=await r.json();if(!r.ok)throw Error(p.detail||'MedNexus could not understand this document.');render(p);$('status').textContent=''}catch(e){$('status').textContent=e.message||'MedNexus could not understand this document.'}finally{$('analyzeBtn').disabled=false}}
$('textTab').onclick=()=>setMode('text');$('fileTab').onclick=()=>setMode('file');$('fileInput').onchange=()=>{$('fileName').textContent=$('fileInput').files[0]?.name||'No file selected'};$('analyzeBtn').onclick=analyze;$('anotherBtn').onclick=()=>{$('results').classList.remove('show');$('workspace').scrollIntoView({behavior:'smooth'})};
